# Generated by Django 5.2.3 on 2025-09-08 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerUp', '0004_favorito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(error_messages={'unique': 'Este CPF já está em uso.'}, max_length=15, unique=True),
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apelido', models.CharField(max_length=100)),
                ('cep', models.CharField(max_length=10)),
                ('uf', models.CharField(max_length=10)),
                ('cidade', models.CharField(max_length=100)),
                ('bairro', models.CharField(max_length=50)),
                ('rua', models.CharField(max_length=200)),
                ('numero', models.CharField(max_length=10)),
                ('complemento', models.CharField(max_length=255, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enderecos', to='powerUp.cliente')),
            ],
        ),
    ]
