# Generated by Django 5.2.3 on 2025-09-09 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerUp', '0005_alter_cliente_cpf_endereco'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereco',
            name='destinatario',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
