# Generated by Django 5.2.3 on 2025-09-10 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerUp', '0006_endereco_destinatario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='complemento',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
