# Generated by Django 5.2.3 on 2025-09-18 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerUp', '0007_alter_endereco_complemento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cartao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apelido', models.CharField(max_length=100)),
                ('titular', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=100)),
                ('bandeira', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('debito', 'Débito'), ('credito', 'Crédito')], max_length=10)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cartoes', to='powerUp.cliente')),
            ],
        ),
    ]
