# Generated by Django 5.2.3 on 2025-10-20 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('powerUp', '0009_carrinho_carrinhoitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrinhoitem',
            name='imagem',
        ),
    ]
