# Generated by Django 5.2.3 on 2025-11-02 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerUp', '0011_pedido_pedidoitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('1', 'Processando'), ('2', 'Enviado'), ('3', 'Entregue'), ('4', 'Recebido'), ('5', 'Cancelado')], max_length=50),
        ),
    ]
