# Generated by Django 5.2.3 on 2025-11-06 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerUp', '0014_solicitacaodevolucao_itemdevolvido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacaodevolucao',
            name='motivo',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
