# Generated by Django 5.2.3 on 2025-11-06 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('powerUp', '0015_alter_solicitacaodevolucao_motivo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitacaodevolucao',
            old_name='foto_video',
            new_name='arquivo',
        ),
    ]
