# Generated by Django 5.2.3 on 2025-11-07 00:55

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerUp', '0016_rename_foto_video_solicitacaodevolucao_arquivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaodevolucao',
            name='total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
