# Generated by Django 5.2.3 on 2025-11-07 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerUp', '0017_solicitacaodevolucao_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacaodevolucao',
            name='status',
            field=models.CharField(choices=[('1', 'Pendente'), ('2', 'Aprovada'), ('3', 'Reembolsado'), ('4', 'Recusada'), ('5', 'Cancelada')], default='1', max_length=50),
        ),
    ]
