# Generated by Django 5.2.3 on 2025-11-21 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerUp', '0019_lote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('status_pedido', 'Status do Pedido'), ('status_devolucao', 'Status da Devolução'), ('mensagem_personalizada', 'Mensagem Geral'), ('promocao', 'Promoção'), ('seguranca', 'Segurança')], default='mensagem_personalizada', max_length=50)),
                ('titulo', models.CharField(max_length=100)),
                ('texto', models.TextField()),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('lida', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='powerUp.cliente')),
            ],
            options={
                'ordering': ['-data_envio'],
            },
        ),
    ]
