# Generated by Django 5.2.3 on 2026-07-16 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerUp', '0021_avaliacaoproduto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(blank=True, error_messages={'unique': 'Este CPF já está em uso.'}, max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefone_celular',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
