# Generated by Django 5.2.3 on 2026-07-27 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerUp', '0022_alter_cliente_cpf_alter_cliente_telefone_celular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(upload_to='produtos/'),
        ),
    ]
